### ISSUE TITLE
No module named 'base_message'

### ISSUE THREAD

**Issue by Strannik74** [lbulygin/telegram-top-posts-bot#1]
❯ python3 main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from chatbase import Message
  File "/usr/local/lib/python3.8/dist-packages/chatbase/__init__.py", line 18, in <module>
    from chatbase.facebook_agent_message import *
  File "/usr/local/lib/python3.8/dist-packages/chatbase/facebook_agent_message.py", line 19, in <module>
    from base_message import Message
ModuleNotFoundError: No module named 'base_message'

**Comment by lblb23** [comment]
@Strannik74  Try to install chatbase from repo:
`pip install git+git://github.com/google/chatbase-python.git `

**Comment by Strannik74** [comment]
Thanks
The error has disappeared
Another appeared
❯ python3 main.py
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    main()
  File "main.py", line 64, in main
    updater = Updater(config["telegram_token"], use_context=True)
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/updater.py", line 160, in __init__
    self.bot = Bot(token,
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 133, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 200, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token

**Comment by lblb23** [comment]
@Strannik74 you need to create own telegram bot and insert token to config.yml 
Manual: https://core.telegram.org/bots#generating-an-authorization-token
